### ISSUE TITLE
Parcelas con zona tipo float

### ISSUE THREAD

**Issue by javiersanp** [OSM-es/CatAtom2Osm#102]
```
2022-02-21 16:11:15,869 - INFO - Comienza el procesado de '39040'
2022-02-21 16:11:16,206 - INFO - Leídos 7672 características en '39040/A.ES.SDGC.CP.39040.cadastralparcel.gml'
2022-02-21 16:11:17,330 - INFO - Leídos 2070 características en '39040/A.ES.SDGC.BU.39040.building.gml'                          
2022-02-21 16:11:17,334 - INFO - Leídos 49 características en '39040/A.ES.SDGC.BU.39040.otherconstruction.gml'
2022-02-21 16:11:26,139 - INFO - Leídos 8060 características en '39040/A.ES.SDGC.BU.39040.buildingpart.gml'                      
2022-02-21 16:11:27,279 - INFO - Leídos 408 características en '39040/A.ES.SDGC.CP.39040.cadastralzoning.gml'                    
Traceback (most recent call last):                                                                                               
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/CatAtom2Osm/catatom2osm/__main__.py", line 195, in <module>
    run()
  File "/opt/CatAtom2Osm/catatom2osm/__main__.py", line 188, in run
    process(options)
  File "/opt/CatAtom2Osm/catatom2osm/__main__.py", line 74, in process
    CatAtom2Osm.create_and_run(a_path, o)
  File "/opt/CatAtom2Osm/catatom2osm/app.py", line 86, in create_and_run
    app.run()
  File "/opt/CatAtom2Osm/catatom2osm/app.py", line 119, in run
    self.process_parcel()
  File "/opt/CatAtom2Osm/catatom2osm/app.py", line 366, in process_parcel
    self.parcel.set_missing_zones()
  File "/opt/CatAtom2Osm/catatom2osm/geo/layer/parcel.py", line 122, in set_missing_zones
    pa["type"] = _("Rustic") if len(pa["zone"]) == 3 else _("Urban")
TypeError: object of type 'float' has no len()

2022-02-21 16:11:38,780 - INFO - Comienza el procesado de '39087'
2022-02-21 16:11:39,183 - INFO - Leídos 10144 características en '39087/A.ES.SDGC.CP.39087.cadastralparcel.gml'
2022-02-21 16:11:40,896 - INFO - Leídos 5374 características en '39087/A.ES.SDGC.BU.39087.building.gml'                          
2022-02-21 16:11:40,901 - INFO - Leídos 69 características en '39087/A.ES.SDGC.BU.39087.otherconstruction.gml'
2022-02-21 16:12:04,629 - INFO - Leídos 26355 características en '39087/A.ES.SDGC.BU.39087.buildingpart.gml'                     
2022-02-21 16:12:08,367 - INFO - Leídos 533 características en '39087/A.ES.SDGC.CP.39087.cadastralzoning.gml'                    
Eliminar partes exteriores:  86%|██████████████████████████████████▌     | 27464/31798 [00:01<00:00, 18577.42it/s, file=building]GEOS exception: TopologyException: side location conflict at 415541.41235 4799437.2269000001
GEOS exception: TopologyException: side location conflict at 415541.41235 4799437.2269000001
Traceback (most recent call last):                                                                                               
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/CatAtom2Osm/catatom2osm/__main__.py", line 195, in <module>
    run()
  File "/opt/CatAtom2Osm/catatom2osm/__main__.py", line 188, in run
    process(options)
  File "/opt/CatAtom2Osm/catatom2osm/__main__.py", line 74, in process
    CatAtom2Osm.create_and_run(a_path, o)
  File "/opt/CatAtom2Osm/catatom2osm/app.py", line 86, in create_and_run
    app.run()
  File "/opt/CatAtom2Osm/catatom2osm/app.py", line 119, in run
    self.process_parcel()
  File "/opt/CatAtom2Osm/catatom2osm/app.py", line 366, in process_parcel
    self.parcel.set_missing_zones()
  File "/opt/CatAtom2Osm/catatom2osm/geo/layer/parcel.py", line 122, in set_missing_zones
    pa["type"] = _("Rustic") if len(pa["zone"]) == 3 else _("Urban")
TypeError: object of type 'float' has no len()

2022-02-21 16:23:28,366 - INFO - Comienza el procesado de '44104'
...

2022-02-21 16:28:27,058 - INFO - Comienza el procesado de '45197'
...

2022-02-21 16:48:17,966 - INFO - Comienza el procesado de '51016'
...

2022-02-21 17:00:14,555 - INFO - Comienza el procesado de '53006'
...
```

**Comment by javiersanp** [comment]
El campo 'label' de zonificación vale 'inf'.

localId tiene valores como:
1E39040M01MARI 
1E39087M01SNIA                                                                                      
1E44104M01ACES
1E45197M01ACII
