### ISSUE TITLE
Error calculando posición media de relación al leer lugares de OSM

### ISSUE THREAD

**Issue by javiersanp** [OSM-es/CatAtom2Osm#112]
2022-11-08 11:14:40,540 - INFO - Generado 'address.geojson'
2022-11-08 11:14:44,974 - INFO - Leído 'current_highway.osm': 78459 nodos, 13696 vías, 64 relaciones
2022-11-08 11:14:47,140 - INFO - Leído 'current_place.osm': 39833 nodos, 1429 vías, 314 relaciones
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/CatAtom2Osm/catatom2osm/__main__.py", line 219, in <module>
    run()
  File "/opt/CatAtom2Osm/catatom2osm/__main__.py", line 212, in run
    process(options)
  File "/opt/CatAtom2Osm/catatom2osm/__main__.py", line 69, in process
    CatAtom2Osm.create_and_run(a_path, o)
  File "/opt/CatAtom2Osm/catatom2osm/app.py", line 101, in create_and_run
    app.run()
  File "/opt/CatAtom2Osm/catatom2osm/app.py", line 147, in run
    self.get_address()
  File "/opt/CatAtom2Osm/catatom2osm/app.py", line 521, in get_address
    self.get_translations(self.address)
  File "/opt/CatAtom2Osm/catatom2osm/app.py", line 677, in get_translations
    place = self.get_place()
  File "/opt/CatAtom2Osm/catatom2osm/app.py", line 697, in get_place
    place.read_from_osm(place_osm)
  File "/opt/CatAtom2Osm/catatom2osm/geo/layer/place.py", line 50, in read_from_osm
    xm = sum(xp) / len(xp)
ZeroDivisionError: division by zero

**Comment by javiersanp** [comment]
Se produce cuando la relación no contiene ninguna vía.
