### ISSUE TITLE
DeprecationWarning: generator 'extractWithoutOrder' raised StopIteration

### ISSUE THREAD

**Issue by javiersanp** [OSM-es/CatAtom2Osm#21]
python3 -m unittest test.test_layer
../usr/local/lib/python3.6/dist-packages/fuzzywuzzy/process.py:245: DeprecationWarning: generator 'extractWithoutOrder' raised StopIteration
  return max(best_list, key=lambda i: i[1])

It could be solved with
```
93:
-            raise StopIteration
+            return
```

**Comment by javiersanp** [comment]
In QGIS 3/Windows, it results in this error:

2018-10-23 11:27:43,677 - DEBUG - Reproyectada la capa 'highway' al CRS 'WGS 84 / UTM zone 28N'
Traceback (most recent call last):
  File "C:\OSGeo4W\apps\Python37\Lib\site-packages\fuzzywuzzy\process.py", line 68, in extractWithoutOrder
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Javier Sánchez\Documents\GitHub\CatAtom2Osm\main.py", line 113, in <module>
    run()
  File "C:\Users\Javier Sánchez\Documents\GitHub\CatAtom2Osm\main.py", line 102, in run
    process(options)
  File "C:\Users\Javier Sánchez\Documents\GitHub\CatAtom2Osm\main.py", line 39, in process
    app.run()
  File "C:\Users\Javier Sánchez\Documents\GitHub\CatAtom2Osm\catatom2osm.py", line 101, in run
    self.read_address()
  File "C:\Users\Javier Sánchez\Documents\GitHub\CatAtom2Osm\catatom2osm.py", line 450, in read_address
    (highway_names, self.is_new) = self.get_translations(self.address)
  File "C:\Users\Javier Sánchez\Documents\GitHub\CatAtom2Osm\catatom2osm.py", line 548, in get_translations
    highway_names = address.get_highway_names(highway)
  File "C:\Users\Javier Sánchez\Documents\GitHub\CatAtom2Osm\layer.py", line 1133, in get_highway_names
    highway_names[name] = hgwnames.match(name, choices)
  File "C:\Users\Javier Sánchez\Documents\GitHub\CatAtom2Osm\hgwnames.py", line 65, in match
    normalized, scorer=fuzz.token_sort_ratio)
  File "C:\OSGeo4W\apps\Python37\Lib\site-packages\fuzzywuzzy\process.py", line 220, in extractOne
    return max(best_list, key=lambda i: i[1])
RuntimeError: generator raised StopIteration
