### ISSUE TITLE
Failed to create file building_packed.shp: Permission denied

### ISSUE THREAD

**Issue by javiersanp** [OSM-es/CatAtom2Osm#23]
During the normal execution In Windows, GDAL raises multiple errors like this. This don't seems to affect the results. The problem occurs while saving changed geometries (self.writer.changeGeometryValues) in layer.PolygonLayer.topology and layer.PolygonLayer.simplify. The only test affected is test_layer.TestConsLayer.test_simplify1, but it occurs randomly.

**Comment by javiersanp** [comment]
The error messages disappears running the program from a devoted simple folder like C:\catastro

**Comment by javiersanp** [comment]
The problem occurs only if the user path includes special characters

**Comment by javiersanp** [comment]
This problem derives in errors like this:
2018-10-29 11:59:40,822 - DEBUG - Reproyectada la capa 'building' al CRS 'WGS 84'
Traceback (most recent call last):
  File "C:\Users\Javier Sßnchez\Documents\GitHub\CatAtom2Osm\main.py", line 113, in <module>
    run()
  File "C:\Users\Javier Sßnchez\Documents\GitHub\CatAtom2Osm\main.py", line 102, in run
    process(options)
  File "C:\Users\Javier Sßnchez\Documents\GitHub\CatAtom2Osm\main.py", line 39, in process
    app.run()
  File "C:\Users\Javier Sßnchez\Documents\GitHub\CatAtom2Osm\catatom2osm.py", line 115, in run
    self.building.set_tasks(self.urban_zoning, self.rustic_zoning)
  File "C:\Users\Javier Sßnchez\Documents\GitHub\CatAtom2Osm\layer.py", line 1247, in set_tasks
    fids = uindex.intersects(feat.geometry().boundingBox())
AttributeError: 'NoneType' object has no attribute 'boundingBox'
