### ISSUE TITLE
Error in building.move_address

### ISSUE THREAD

**Issue by javiersanp** [OSM-es/CatAtom2Osm#25]
During second processing of 08900 with 1.2dev, QGIS 3.2.3

2018-11-05 00:04:13,076 - DEBUG - Simplificados 158663 vértices en la capa 'building'
Traceback (most recent call last):
  File "/home/javier/osm-es/CatAtom2Osm/main.py", line 113, in <module>
    run()
  File "/home/javier/osm-es/CatAtom2Osm/main.py", line 102, in run
    process(options)
  File "/home/javier/osm-es/CatAtom2Osm/main.py", line 39, in process
    app.run()
  File "/home/javier/osm-es/CatAtom2Osm/catatom2osm.py", line 112, in run
    self.building.move_address(self.address)
  File "/home/javier/osm-es/CatAtom2Osm/layer.py", line 1574, in move_address
    r = Geometry.get_multipolygon(pg)[0][0]
IndexError: list index out of range

**Comment by javiersanp** [comment]
Problem observed only in one machine and can't reproduce it. It's difficult to debug due to issue #28.

**Comment by javiersanp** [comment]
It occurs by the generation of geometries with unknow type in the shapefiles.
geom.wkbType() == WKBUnknown
