### ISSUE TITLE
Error in get_multipolygon

### ISSUE THREAD

**Issue by javirg** [OSM-es/CatAtom2Osm#31]
I run into the following error when attempting to process any town:

> Traceback (most recent call last):
  File "/home/xrg/CatAtom2Osm/main.py", line 113, in <module>
    run()
  File "/home/xrg/CatAtom2Osm/main.py", line 102, in run
    process(options)
  File "/home/xrg/CatAtom2Osm/main.py", line 39, in process
    app.run()
  File "/home/xrg/CatAtom2Osm/catatom2osm.py", line 103, in run
    self.process_zoning()
  File "/home/xrg/CatAtom2Osm/catatom2osm.py", line 261, in process_zoning
    self.urban_zoning.merge_adjacents()
  File "/home/xrg/CatAtom2Osm/layer.py", line 945, in merge_adjacents
    (groups, geometries) = self.get_adjacents_and_geometries()
  File "/home/xrg/CatAtom2Osm/layer.py", line 643, in get_adjacents_and_geometries
    parents_per_vertex, geometries = self.get_parents_per_vertex_and_geometries()
  File "/home/xrg/CatAtom2Osm/layer.py", line 634, in get_parents_per_vertex_and_geometries
    for point in Geometry.get_vertices_list(feature):
  File "/home/xrg/CatAtom2Osm/layer.py", line 200, in get_vertices_list
    return [point for part in Geometry.get_multipolygon(feature) \
  File "/home/xrg/CatAtom2Osm/layer.py", line 193, in get_multipolygon
    if geom.wkbType() == WKBPolygon:
AttributeError: 'NoneType' object has no attribute 'wkbType'

Bug thrown using Debian 9, Python 2.7.13, QGIS 2.14.11 and GDAL 2.1.2.

**Comment by javiersanp** [comment]
Gracias por informar. 
Reproducido en Ubuntu centrado en la opción -z (zoning). Ocurre sólo con archivos de Catastro descargados recientemente, no con antiguos.

**Comment by javiersanp** [comment]
Los datos de catastro publicados recientemente contienen características en la capa urban zoning con geometría None y sin campos.

**Comment by javiersanp** [comment]
Esa característica es añadida por el método append de ZoningLayer

**Comment by javiersanp** [comment]
El motivo es que la capa contiene una zona con geometría vacía.
```
l = iface.activeLayer()
exp=QgsExpression("levelName = '(1:MANZANA )'")
f = l.getFeatures(request).next()
>>> f['inspireId_localId']
NULL
>>> f['label']
NULL
>>> f.geometry().asMultiPolygon()
[]
```
