### ISSUE TITLE
Error in pbar.clean()

### ISSUE THREAD

**Issue by javirg** [OSM-es/CatAtom2Osm#32]
When processing a big city, the program stops at this point. No problems found with smaller towns.

> Traceback (most recent call last):
  File "/home/xrg/CatAtom2Osm/main.py", line 113, in <module>
    run()
  File "/home/xrg/CatAtom2Osm/main.py", line 102, in run
    process(options)
  File "/home/xrg/CatAtom2Osm/main.py", line 39, in process
    app.run()
  File "/home/xrg/CatAtom2Osm/catatom2osm.py", line 121, in run
    if self.building.conflate(current_bu_osm):
  File "/home/xrg/CatAtom2Osm/layer.py", line 1674, in conflate
    pbar.clean()
AttributeError: 'tqdm' object has no attribute 'clean'

Using Debian 9, Python 2.7.13, QGIS 2.14.11 and GDAL 2.1.2.

**Comment by javiersanp** [comment]
Easy
