### ISSUE TITLE
Error unicode en barras de progreso

### ISSUE THREAD

**Issue by javiersanp** [OSM-es/CatAtom2Osm#48]
Usando la misma versión que egofer me da exactamente el mismo error.

Usando la versión en desarrollo me da error en la segunda pasada pero creo que es por el mismo motivo porque ha dejado de funcionar a la vez.

```
parallels@parallels-Parallels-Virtual-Platform:~/Desktop/catastro$ catatom2osm 37009 --log DEBUG
2019-11-16 15:41:15,293 - DEBUG - Usando Python 2.7.15
2019-11-16 15:41:15,293 - DEBUG - Running with lxml.etree
2019-11-16 15:41:16,213 - DEBUG - Inicializada la API de QGIS 2.18.17
2019-11-16 15:41:16,214 - DEBUG - Usando GDAL 2.2.3
2019-11-16 15:41:16,215 - INFO - Comienza el procesado de '37009'
2019-11-16 15:41:16,327 - INFO - Leídos 43 características en '37009/A.ES.SDGC.CP.37009.cadastralzoning.gml'
Agregar: 100%|██████████| 43/43 [00:00<00:00, 536.83it/s, file=rustic_zoning.shp]
2019-11-16 15:41:16,437 - DEBUG - Cargados 5 características en 'rusticzoning' desde 'cadastralzoning.gml'
2019-11-16 15:41:17,883 - INFO - Municipio: 'Alba de Yeltes'
Agregar: 100%|██████████| 43/43 [00:00<00:00, 2271.42it/s, file=urban_zoning.shp]
2019-11-16 15:41:17,911 - DEBUG - Cargados 37 características en 'urbanzoning' desde 'cadastralzoning.gml'
2019-11-16 15:41:17,912 - DEBUG - 5 multipolígonos divididos a 10 poligonos en la capa 'urbanzoning'
2019-11-16 15:41:17,937 - INFO - Leídos 327 características en '37009/A.ES.SDGC.AD.37009.gml'
2019-11-16 15:41:17,955 - INFO - Leídos 1 características en '37009/A.ES.SDGC.AD.37009.gml'
2019-11-16 15:41:17,973 - INFO - Leídos 18 características en '37009/A.ES.SDGC.AD.37009.gml'
Agregar: 100%|██████████| 327/327 [00:00<00:00, 4813.43it/s, file=address.shp]
2019-11-16 15:41:18,094 - DEBUG - Cargados 327 características en 'address' desde 'address.gml'
Unir campo: 100%|██████████| 328/328 [00:00<00:00, 8039.01it/s, file=address.shp]
2019-11-16 15:41:18,160 - DEBUG - Combinado 'postaldescriptor.gml' a 'address'
Unir campo: 100%|██████████| 345/345 [00:00<00:00, 8891.97it/s, file=address.shp]
2019-11-16 15:41:18,214 - DEBUG - Combinado 'thoroughfarename.gml' a 'address'
2019-11-16 15:41:18,265 - INFO - Generado 'address.geojson'
2019-11-16 15:41:18,304 - DEBUG - Eliminadas 7 direcciones rechazadas por nombre de vial
  0%|          | 0/42 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/parallels/catastro/CatAtom2Osm-development/main.py", line 113, in <module>
    run()
  File "/home/parallels/catastro/CatAtom2Osm-development/main.py", line 102, in run
    process(options)
  File "/home/parallels/catastro/CatAtom2Osm-development/main.py", line 39, in process
    app.run()
  File "/home/parallels/catastro/CatAtom2Osm-development/catatom2osm.py", line 103, in run
    self.process_zoning()
  File "/home/parallels/catastro/CatAtom2Osm-development/catatom2osm.py", line 260, in process_zoning
    self.urban_zoning.topology()
  File "/home/parallels/catastro/CatAtom2Osm-development/layer.py", line 689, in topology
    pbar = self.get_progressbar(_("Topology"), len(geometries))
  File "/home/parallels/catastro/CatAtom2Osm-development/layer.py", line 583, in get_progressbar
    pbar.set_description(description)
  File "/home/parallels/.local/lib/python2.7/site-packages/tqdm/std.py", line 1312, in set_description
    self.refresh()
  File "/home/parallels/.local/lib/python2.7/site-packages/tqdm/std.py", line 1274, in refresh
    self.display()
  File "/home/parallels/.local/lib/python2.7/site-packages/tqdm/std.py", line 1397, in display
    self.sp(self.__repr__() if msg is None else msg)
  File "/home/parallels/.local/lib/python2.7/site-packages/tqdm/std.py", line 1042, in __repr__
    return self.format_meter(**self.format_dict)
  File "/home/parallels/.local/lib/python2.7/site-packages/tqdm/std.py", line 469, in format_meter
    nobar = bar_format.format(bar=full_bar, **format_dict)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in position 7: ordinal not in range(128)
Exception UnicodeEncodeError: UnicodeEncodeError('ascii', u'Topolog\xeda:   0%|', 7, 8, 'ordinal not in range(128)') in <object repr() failed> ignored

```
Con:

- Python 2.7.15
- CatAtom2Osm 1.2 dev
- GDAL 2.2.3
- QGIS 2.18.17

_Originally posted by @JorgeSanzS in https://github.com/OSM-es/CatAtom2Osm/issues/47#issuecomment-554643714_

**Comment by javiersanp** [comment]
Es un problema externo que se ha trasladado a tqdm/tqdm#851. Está corregido y se publicará en la versón tqdm/tqdm#852
