### ISSUE TITLE
Mejoras división de municipio. 

### ISSUE THREAD

**Issue by javiersanp** [OSM-es/CatAtom2Osm#84]
En relación con #78.

Un límite administrativo tal como se baja de OSM queda como LineString al exportar a geojson, por ejemplo. Si se dibuja a mano la vía, puede ser un error común olvidarse de convertir a multipolígono.

Esto se evitaría convirtiendo internamente a multipoligo cualquier vía cerrada. 

También podría ser cómodo para el usuario indicar el id de un límite administrativo y que el programa se encargue de descargarlo directamente. En este caso las consultas de overpass se pueden limitar a ese límite en lugar del bbox.

**Comment by javiersanp** [comment]
**catastro@e43bc24ad4aa:~/test$ catatom2osm -s 05015sur.osm 05015
ERROR 1: posix_spawnp() failed
2022-01-23 10:39:57,679 - INFO - Comienza el procesado de '05015'
2022-01-23 10:39:57,706 - INFO - Leídos 37 características en '05015/A.ES.SDGC.CP.05015.cadastralzoning.gml'
2022-01-23 10:39:59,089 - INFO - Municipio: 'Arevalillo'                                                                
2022-01-23 10:39:59,133 - INFO - Leídos 391 características en '05015/A.ES.SDGC.BU.05015.building.gml'
2022-01-23 10:39:59,172 - INFO - Leídos 618 características en '05015/A.ES.SDGC.BU.05015.buildingpart.gml'
2022-01-23 10:39:59,173 - INFO - La capa '05015/A.ES.SDGC.BU.05015.otherconstruction.gml' está vacía
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/CatAtom2Osm/catatom2osm/__main__.py", line 138, in <module>
    run()
  File "/opt/CatAtom2Osm/catatom2osm/__main__.py", line 130, in run
    process(options)
  File "/opt/CatAtom2Osm/catatom2osm/__main__.py", line 68, in process
    CatAtom2Osm.create_and_run(a_path, options)
  File "/opt/CatAtom2Osm/catatom2osm/app.py", line 104, in create_and_run
    app.run()
  File "/opt/CatAtom2Osm/catatom2osm/app.py", line 134, in run
    self.get_building()
  File "/opt/CatAtom2Osm/catatom2osm/app.py", line 259, in get_building
    self.split_zoning()
  File "/opt/CatAtom2Osm/catatom2osm/app.py", line 228, in split_zoning
    self.urban_zoning.remove_outside_features(self.split, self.zone)
  File "/opt/CatAtom2Osm/catatom2osm/layer.py", line 1224, in remove_outside_features
    split.transform(crs_transform)
AttributeError: 'bool' object has no attribute 'transform'
**

**Comment by javiersanp** [comment]
Error con osm

**Comment by javiersanp** [comment]
a46e65b2
v2.6.0
