### ISSUE TITLE
ERROR 1: XML parsing of GML file failed

### ISSUE THREAD

**Issue by javiersanp** [OSM-es/CatAtom2Osm#94]
Ocurre en 03050 03065 11032 13019.

```
ERROR 1: XML parsing of GML file failed : not well-formed (invalid token) at line 203847, column 49                      
2022-02-18 08:10:35,946 - INFO - Leídos 5437 características en '03050/A.ES.SDGC.CP.03050.cadastralparcel.gml'
Agregar:   0%|                                                                                  | 0/5437 [00:00<?, ?it/s]ERROR 1: XML parsing of GML file failed : not well-formed (invalid token) at line 203847, column 49
Agregar:   0%|                                                            | 0/5437 [00:00<?, ?it/s, file=cadastralparcel]
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/CatAtom2Osm/catatom2osm/__main__.py", line 154, in <module>
    run()
  File "/opt/CatAtom2Osm/catatom2osm/__main__.py", line 142, in run
    process(options)
  File "/opt/CatAtom2Osm/catatom2osm/__main__.py", line 67, in process
    CatAtom2Osm.create_and_run(a_path, o)
  File "/opt/CatAtom2Osm/catatom2osm/app.py", line 85, in create_and_run
    app.run()
  File "/opt/CatAtom2Osm/catatom2osm/app.py", line 111, in run
    self.get_parcel()
  File "/opt/CatAtom2Osm/catatom2osm/app.py", line 204, in get_parcel
    raise ValueError(_("No parcels data"))
ValueError: No hay parcelas
```

**Comment by javiersanp** [comment]
Error de codificación de los archivos originales.

```
$ zcat 03050/A.ES.SDGC.CP.03050.zip | awk 'NR == 203847'
    <cp:CadastralParcel gml:id="ES.SDGC.CP.695400�YH2565S">
$ zcat 03065/A.ES.SDGC.CP.03065.zip | awk 'NR == 1822531'
    <cp:CadastralParcel gml:id="ES.SDGC.CP.106090�YH0316A">
$ zcat 11032/A.ES.SDGC.CP.11032.zip | awk 'NR == 420926'
    <cp:CadastralParcel gml:id="ES.SDGC.CP.62226�1QA3762C">
$ zcat 13019/A.ES.SDGC.CP.13019.zip | awk 'NR == 117'
    <cp:CadastralParcel gml:id="ES.SDGC.CP.2P13019P02PE�A">
```
cp1251
    <cp:CadastralParcel gml:id="ES.SDGC.CP.695400їYH2565S">
ISO-8859-1
    <cp:CadastralParcel gml:id="ES.SDGC.CP.695400¿YH2565S">
