### ISSUE TITLE
ERROR - 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by javiersanp** [OSM-es/CatAtom2Osm#95]
Ocurre en 03021.

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/CatAtom2Osm/catatom2osm/__main__.py", line 154, in <module>
    run()
  File "/opt/CatAtom2Osm/catatom2osm/__main__.py", line 142, in run
    process(options)
  File "/opt/CatAtom2Osm/catatom2osm/__main__.py", line 67, in process
    CatAtom2Osm.create_and_run(a_path, o)
  File "/opt/CatAtom2Osm/catatom2osm/app.py", line 85, in create_and_run
    app.run()
  File "/opt/CatAtom2Osm/catatom2osm/app.py", line 119, in run
    self.get_address()
  File "/opt/CatAtom2Osm/catatom2osm/app.py", line 448, in get_address
    self.get_translations(self.address)
  File "/opt/CatAtom2Osm/catatom2osm/app.py", line 605, in get_translations
    highway_names = address.get_highway_names(highway)
  File "/opt/CatAtom2Osm/catatom2osm/geo/layer/address.py", line 110, in get_highway_names
    highway_names[name] = hgwnames.match(name, choices)
  File "/opt/CatAtom2Osm/catatom2osm/hgwnames.py", line 55, in match
    parsed_name = parse(name)
  File "/opt/CatAtom2Osm/catatom2osm/hgwnames.py", line 18, in parse
    name = name.split(';')[0] # Remove additional information
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by javiersanp** [comment]
Error en datos originales

03.021.960.5A.3583407YH00000
   <AD:component xlink:href="#ES.SDGC.PD.03.021.3450" />
   <AD:component xlink:href="#ES.SDGC.TN.03.021.960" /> <-- no está presente
   <AD:component xlink:href="#ES.SDGC.AU.03.021" />
